
### Author: ANDRES LEGUIZAMON / CARLOS SANCHEZ / GERMAN RODRIGUEZ / SOFIA OCAMPO 
### 2025
### TODO : LICENSE / COPYRIGHT 



### DESCRIPTION: Class that takes a list of transactions and constructs the quantity flow matrix between agents for each good 


# This class processes the information from the statements and extracts relevant data for auditing.


class StatementInfoParser:

    def __init__(self):
        pass

    def extract_info_tuple(self, agent_1 , agent_2, account , reports):
        """
        This method is designed to extract specific account information between two agents.

        This is used to calculate symmetry measures 

        It is designed to handle the reports dictionary generated by the Economy Class

        EX of how economy class calls agents statement information:

        FZ_utility = reports['ZF']['Net Profit']

        NCT_utility = reports['NCT']['Net Profit']

        
        """

        agent_1_info = reports['reports'][agent_1][account]
        agent_2_info = reports['reports'][agent_2][account]

        return agent_1_info, agent_2_info
