
from abc import ABC, abstractmethod
from typing import List , Tuple , Union 

from ..order.orders import BaseBuyOrder, BaseProductionOrder

### Author: ANDRES LEGUIZAMON / CARLOS SANCHEZ / GERMAN RODRIGUEZ / SOFIA OCAMPO 
### 2025
### TODO : LICENSE / COPYRIGHT 

### DESCRIPTION: Class that acts as interface bridge between the sequences of trasnactions generated by the planner and the order data structure 
# Handled by the economy module. 


class OrderParser(ABC):
    """
    Abstract base class for parsing orders.
    """

    @abstractmethod
    def parse_order(self, order_data: dict) -> List[Union[BaseBuyOrder, BaseProductionOrder]]:
        """
        Parses order data in a defined format into a BaseBuyOrder or BaseProductionOrder object 
        """
        pass





class BuyOrderParser(OrderParser):
    """
    Concrete implementation of OrderParser for buy orders.
    Parses order data into BaseBuyOrder objects.

    This is adapted for the specific output format of the planner module 

    Example of Planner Buy Order output : (1, ('ZF', 'MKT'), 'Buy', 'RawMaterial')
    
    -step : step number of the order in the sequence
    -(buyer, seller) : agents that are involved in the order
    -action : type of order (Buy)
    -good : good that is involved in the order


    """

    def parse_order(self, order_data: Tuple) -> BaseBuyOrder:
        step, (buyer, seller), action, good = order_data
        return BaseBuyOrder(buyer = buyer, seller = seller, good = good)
    



class ProductionOrderParser(OrderParser):
    """
    Concrete implementation of OrderParser for production orders.
    Parses order data into productionOrder objects.

    This is adapated for the specific output format of the planner module 

    Example of Planner Produce Order output : (2, ('NCT',), 'Produce', 'Stage1')
    
    -step : step number of the order in the sequence
    -(Producer, ) : agents that are involved in the order
    -action : type of order (Produce)
    -good : good that is involved in the production order


    """

    def parse_order(self, order_data: Tuple) -> BaseProductionOrder:
        step, (producer,), action, good = order_data
        return BaseProductionOrder(producer=producer, produced_good=good)
    


class PlannerParser:
    """
    Class that uses the specific parsers to parse orders from the planner module.
    """

    def __init__(self):
        """
        Initializes the PlannerParser object with the necessary parsers
        for the different types of orders.
        """
        
        self.buy_order_parser = BuyOrderParser()
        self.production_order_parser = ProductionOrderParser()

    def parse_orders(self, orders_data: List[Tuple]) -> List[Union[BaseBuyOrder, BaseProductionOrder]]:
        parsed_orders = []
        for order_data in orders_data:
            if order_data[2] == 'Buy':
                parsed_orders.append(self.buy_order_parser.parse_order(order_data))
            elif order_data[2] == 'Produce':
                parsed_orders.append(self.production_order_parser.parse_order(order_data))
        return parsed_orders