
### Author: ANDRES LEGUIZAMON / CARLOS SANCHEZ / GERMAN RODRIGUEZ / SOFIA OCAMPO 
### 2025
### TODO : LICENSE / COPYRIGHT 

### DESCRIPTION: Class Economy that represents the fixed environment with a given genome 




from networkx import DiGraph 

from src.simulation.economy.production_process.production_graph import ProductionGraph


from src.simulation.economy.production_process.production_process import ProductionProcess 

from src.simulation.economy.order_book.utils.order_parser import PlannerParser 

from src.simulation.economy.order_book.utils.order_completer import OrderCompleter

from src.simulation.planner.planner  import Planner 

from src.simulation.economy.agent.agent import Agent

from typing import List, Dict , Tuple , Optional

from src.simulation.economy.order_book.utils.price_looker import PriceLooker 

from src.simulation.economy.assets.good import Good
import numpy as np 

from src.simulation.economy.order_book.order.orders import BuyOrder, ProductionOrder

from src.simulation.economy.invisible_hand.global_accountant import Accountant

from src.simulation.economy.agent.reporting.income_statement import generate_income_statement


from src.simulation.economy.auditor.auditor import Auditor

from decimal import Decimal

class Economy():
    def __init__(
        self,
        production_graph: Optional[List],
        pmatrix: np.ndarray,
        agents_information: Dict[str, Dict[str, List[int]]],
        genome: List[int],
        genome_auditor: Optional[List[int]] = None,   # kept optional; defaults handled below
    ):
        """
        Initializes an Economy object with the given parameters.

        Args:
            production_graph (Optional[List]): List of edges in the production graph.
            pmatrix (np.ndarray): 3-dimensional numpy array with the price matrix.
            agents_information (Dict[Dict]): Dictionary with the information of the agents.
            genome (List[int]): Genome of the economy.

        Attributes:
            production_graph (ProductionGraph): Object with the production graph.
            general_production_process (ProductionProcess): Object with the general production process.
            price_looker (PriceLooker): Object that determines the price for a given order based on the agent's location and the good involved.
            order_completer (OrderCompleter): Object that completes a buy order by determining the price based on the agent's location and the good involved.
            planner_parser (PlannerParser): Object that acts as interface bridge between the sequences of transactions generated by the planner and the order data structure.
            planner (Planner): Object with the planner.
            agents (Dict[Agent]): Dictionary with the agents.
        """
        # Save parameters for reset
        self.agents_information = agents_information
        self.original_production_graph = production_graph
        self.original_pmatrix = pmatrix
        self.genome = genome

        # Domain bootstrap
        self.production_graph = ProductionGraph(DiGraph(production_graph))
        self.general_production_process = ProductionProcess(self.production_graph)

        agents_price_mapping = {
            info['type']: info['price_mapping']
            for info in agents_information.values()
        }
        self.price_looker = PriceLooker(pmatrix, agents_price_mapping, self.production_graph)
        self.order_completer = OrderCompleter(self.price_looker)
        self.planner_parser = PlannerParser()
        self.planner = Planner(self.general_production_process)

        # Auditor genome normalization (defensive defaults and invariants).
        # Ensures: length >= 2 (Auditor uses [0] and [1]), avoids zero denominator,
        # and provides a full 25-genes default when nothing is supplied.
        def _normalize_auditor_genome(g):
            # Default: 25 ones if not provided or empty.
            if not g:
                return [1] * 25
            # Robust int conversion.
            try:
                arr = [int(x) for x in g]
            except Exception:
                arr = [1] * 25
            # Guarantee at least 2 genes for mix calculation.
            if len(arr) == 0:
                arr = [1] * 25
            elif len(arr) == 1:
                arr = [arr[0], 1] + [1] * 23  # extend to 25 (keeps semantics)
            elif len(arr) == 2:
                arr = [arr[0], arr[1]] + [1] * 23
            # Avoid zero denominator in mix = a0 / (a0 + a1).
            if (arr[0] + arr[1]) == 0:
                arr[0], arr[1] = 1, 1
            return arr

        auditor_genome = _normalize_auditor_genome(genome_auditor)
        self.auditor = Auditor(auditor_genome)

        self.global_accountant = Accountant()

        # Agents construction
        self.agents = {
            agent_name: Agent(
                type=info['type'],
                global_production_graph=self.production_graph,
                inventory_strategy=info['inventory_strategy'],
                firm_related_goods=info['firm_related_goods'],
                income_statement_type=info['income_statement_type'],
                accounts_yaml_path=info['accounts_yaml_path']
            )
            for agent_name, info in agents_information.items()
        }

        # Initialize the market with primary goods
        required_quantities = self.general_production_process.get_required_quantities()
        good_classification = self.general_production_process.get_goods_classification()

        if self.agents.get("MKT") is None:
            raise ValueError("Market agent 'MKT' must be defined in agents_information")

        market = self.agents["MKT"]
        for good, quantity in required_quantities.items():
            if good_classification[good] == "primary":
                for _ in range(1, quantity + 1):
                    good_instance = Good(type=good, price=0)
                    market.get_inventory().add_good(good_instance)

        # Plan execution (orders are computed and completed upfront)
        transaction_sequence = self.planner.execute_plan(self.genome)
        base_orders = self.planner_parser.parse_orders(transaction_sequence)
        self.orders = self.order_completer.complete_orders(base_orders)


    
    def process_buy_order(self, buy_order):

        if not isinstance(buy_order, BuyOrder):

            raise TypeError("argument must be an instance of BuyOrder")
       
        buyer = buy_order.buyer
       
        seller = buy_order.seller
       
        good = buy_order.good
       
        price = buy_order.price
       
        buyer_agent = self.agents[buyer]
       
        seller_agent = self.agents[seller]
       
        good_instance = seller_agent.get_inventory().get_unit(good)

        seller_agent.get_inventory().remove_instance(good_instance)
       
        buyer_agent.get_inventory().add_good(good_instance)
       
        return (buyer_agent, seller_agent, good_instance, price)
    

    def execute_buy_order(self, buy_order):
         
        if not isinstance(buy_order, BuyOrder):

            raise TypeError("argument must be an instance of BuyOrder")
         
        transaction_info = self.process_buy_order(buy_order)

        price = transaction_info[3]

        # Modify price and cost 

        good_instance = transaction_info[2]

        good_instance.price = price
        good_instance.cost = good_instance.price
        # Record Transaction 
        self.global_accountant.record_transaction(transaction_info)
        good_instance.last_cost = good_instance.cost

        
    
    
    def process_production_order(self, production_order):

        if not isinstance(production_order, ProductionOrder):

            raise TypeError("argument must be an instance of ProductionOrder")
        
        producer = production_order.producer

        produced_good = production_order.produced_good
        
        producer_agent = self.agents[producer]
        
        # Produce the good and call the instance
        
        production_menu = producer_agent.generate_produce_menu(produced_good)

        production_menu_tuple = list(production_menu.items())

        producer_agent.produce_good(produced_good)

        good_instance = producer_agent.get_inventory().inventory[produced_good][-1]  # Get the last produced good instance

        return (producer_agent, good_instance, production_menu_tuple)
    

    def execute_production_order(self, production_order):
         
        if not isinstance(production_order, ProductionOrder):

            raise TypeError("argument must be an instance of ProductionOrder")
         
        transaction_info = self.process_production_order(production_order)

        self.global_accountant.record_transaction(transaction_info)


    def process_order(self, order):

        """
        Generates the accounting information for a given order.
        
        Args:
            order (Union[BuyOrder, ProductionOrder]): The order for which to generate accounting information.
        
        Returns:
            Tuple: A tuple containing the relevant accounting information.
        """
        
        if isinstance(order, BuyOrder):
            return self.process_buy_order(order)
        
        elif isinstance(order, ProductionOrder):
            return self.process_production_order(order)
        
        else:
            raise ValueError("Order must be either a BuyOrder or a ProductionOrder"
                             f"but got {type(order)}")
        

    def execute_order(self, order):

        """
        Executes a given order and records the transaction in the global accountant.
        
        Args:
            order (Union[BuyOrder, ProductionOrder]): The order to be executed.
        """
        
        if isinstance(order, BuyOrder):
            self.execute_buy_order(order)
        
        elif isinstance(order, ProductionOrder):
            self.execute_production_order(order)
        
        else:
            raise ValueError("Order must be either a BuyOrder or a ProductionOrder"
                             f"but got {type(order)}")
    
    def get_agents(self) -> Dict[str, Agent]:
        """
        Returns the agents in the economy.
        
        Returns:
            Dict[str, Agent]: A dictionary of agents with their names as keys.
        """
        return self.agents
    
    
    def execute_plan(self, plan:List): 
        
        for order in plan:
            self.execute_order(order)

    
    def get_reports(self):
        
        """
        Generates reports for all agents except the market agent.
        
        Returns:
            List: A list of reports for each agent.

        """
        self.execute_plan(self.orders)

        report_list = [agent for agent_name, agent in self.agents.items() if agent_name != 'MKT']
        
        dict_reports = {agent.type: generate_income_statement(agent) for agent in report_list}

        total_utility = sum(report['Net Profit'] for report in dict_reports.values())

        return {'reports':dict_reports , 'utility': total_utility}

    def get_profit(self) -> Dict[str, float]:
        """
        Convenience: Reports the total profit per agent and for the economy.
        """
        rep = self.get_reports() or {}
        rr = rep.get("reports", {}) or {}

        zf = float(rr.get("ZF", {}).get("Net Profit", 0) or 0)
        nct = float(rr.get("NCT", {}).get("Net Profit", 0) or 0)

        return {"ZF": zf, "NCT": nct, "total": zf + nct}

    def GA_interface_utility(self):
        

        reports = self.get_reports()

        FZ_utility = reports['reports']['ZF']['Net Profit']

        NCT_utility = reports['reports']['NCT']['Net Profit']

        utility = FZ_utility + NCT_utility
        
        return {'ZF': FZ_utility, 'NCT': NCT_utility}, utility
    

    def GA_coevolution_function_1(self):

        reports = self.get_reports()

        FZ_profit = reports['reports']['ZF']['Net Profit']

        NCT_profit = reports['reports']['NCT']['Net Profit']

        tax_expense = reports['reports']['ZF']['Tax Expense'] + reports['reports']['NCT']['Tax Expense']

        profit = FZ_profit + NCT_profit

        pmatrix = self.original_pmatrix

        pgraph = self.original_production_graph

        transaction_list = self.orders


        audit_score = self.auditor.run_audit(pmatrix , transaction_list, pgraph , reports)

        audit_score= float(audit_score)
        fitness_evader = float(tax_expense) * (1 - audit_score)
        fitness_auditor = -float(tax_expense) * (1 - audit_score)

        return (fitness_evader , fitness_auditor)
    
    def GA_coevolution_function_ev_neutral_aud_neutral(self):

        reports = self.get_reports()

        FZ_profit = reports['reports']['ZF']['Net Profit']

        NCT_profit = reports['reports']['NCT']['Net Profit']

        tax_expense = reports['reports']['ZF']['Tax Expense'] + reports['reports']['NCT']['Tax Expense']

        profit = FZ_profit + NCT_profit

        profit = float(profit)

        pmatrix = self.original_pmatrix

        pgraph = self.original_production_graph

        transaction_list = self.orders


        audit_score = self.auditor.run_audit(pmatrix , transaction_list, pgraph , reports)


        audit_score= float(audit_score)

        fitness_evader = float(tax_expense) * (1 - audit_score) + (audit_score)*(-profit)

        fitness_auditor = -float(tax_expense) * (1 - audit_score)+ (audit_score)*(float(tax_expense))

        return (fitness_evader , fitness_auditor)
    
    
    

    
